apiVersion: v1
kind: Service
metadata:
  labels:
    run: mongodb
  name: mongodb
spec:
  ports:
  - nodePort: 31675
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: mongodb
  type: NodePort
