apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: muzix
  name: muzix
spec:
  replicas: 1
  selector:
    matchLabels:
      run: muzix
  template:
    metadata:
      labels:
        run: muzix
    spec:
      containers:
      - image: satchida761/muzix-app
        imagePullPolicy: Always
        name: muzix
        ports:
        - containerPort: 8090
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: muzix
  name: muzix
spec:
  ports:
  - nodePort: 30404
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: muzix
  type: NodePort